site_name: Networking+
site_description: Documentation template built with MkDocs
site_author: Your Name
site_url: https://yourusername.github.io/your-repo-name/

# Repository
repo_name: yourusername/your-repo-name
repo_url: https://github.com/yourusername/your-repo-name

# Copyright
copyright: Copyright &copy; 2025 Your Name

# Theme Configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JavaScript
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js

# Navigation Structure
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Configuration: user-guide/configuration.md
    - Customization: user-guide/customization.md
    - Deployment: user-guide/deployment.md
  - API Reference: api-reference/index.md
