name: Deploy MkDocs Documentation
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Print deployment information
        run: |
          echo "::group::Deployment Information"
          echo "Repository: ${{ github.repository }}"
          echo "GitHub Pages URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "Deployment branch: gh-pages"
          echo "::endgroup::"
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
      - name: Print deployment success
        run: |
          echo "::group::Deployment Complete"
          echo "Documentation successfully deployed to GitHub Pages"
          echo "URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "::endgroup::"
